from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"

STORY_METADATA_PATH = BASE_DIR / "PageTitle2026.csv"
STORY_METRICS_PATH = BASE_DIR / "Stories2026.csv"
SERVICE_ACCOUNT_PATH = BASE_DIR / "service_account.json"

PV_THRESHOLD_PERCENT = 0.001
NLP_PIPELINE_VERSION = "2026-07-10-editorial-keybert-v5"

MIN_KEYWORD_LENGTH = 3

# Direct title search keeps registered two-letter abbreviations even when an
# editor enters them in lowercase. Uppercase and dotted two-letter query forms
# are recognized automatically; this registry supplies their case-insensitive
# equivalents and can be extended as editorial terminology evolves.
TWO_LETTER_SEARCH_ABBREVIATIONS = frozenset(
    {
        "ai",
        "ms",
        "pf",
        "pm",
        "po",
        "uk",
        "us",
    }
)

STOP_WORDS = {
    "a",
    "about",
    "above",
    "after",
    "again",
    "against",
    "all",
    "am",
    "amid",
    "an",
    "and",
    "any",
    "are",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "below",
    "between",
    "both",
    "but",
    "by",
    "can",
    "did",
    "do",
    "does",
    "doing",
    "down",
    "end",
    "during",
    "each",
    "few",
    "for",
    "from",
    "further",
    "had",
    "has",
    "have",
    "having",
    "he",
    "her",
    "here",
    "hers",
    "herself",
    "him",
    "himself",
    "his",
    "how",
    "i",
    "if",
    "in",
    "into",
    "is",
    "it",
    "its",
    "itself",
    "just",
    "latest",
    "live",
    "me",
    "more",
    "most",
    "my",
    "myself",
    "no",
    "nor",
    "not",
    "now",
    "of",
    "off",
    "on",
    "once",
    "only",
    "or",
    "other",
    "our",
    "ours",
    "ourselves",
    "out",
    "over",
    "own",
    "same",
    "she",
    "should",
    "so",
    "some",
    "such",
    "than",
    "that",
    "the",
    "their",
    "theirs",
    "them",
    "themselves",
    "then",
    "there",
    "these",
    "they",
    "this",
    "those",
    "through",
    "to",
    "too",
    "under",
    "until",
    "up",
    "very",
    "was",
    "we",
    "were",
    "what",
    "when",
    "where",
    "which",
    "while",
    "who",
    "whom",
    "why",
    "will",
    "with",
    "update",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
}
